# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
        exclude: '^\.vscode/'
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic>=2.10.1", "supabase>=2.17.0"]
        args: ['--config-file=pyproject.toml', '--ignore-missing-imports', 'src/']
        pass_filenames: false
        always_run: true
